import { db } from '@/db';
import { jobs } from '@/db/schema';

async function main() {
    const sampleJobs = [
        {
            title: 'Senior Software Engineer',
            company: 'TechCorp',
            description: 'We are seeking an experienced Senior Software Engineer to lead our backend development team. You will be responsible for architecting scalable solutions and mentoring junior developers.',
            location: 'San Francisco, CA',
            salaryRange: '$120k - $180k',
            jobUrl: 'https://techcorp.com/careers/senior-software-engineer',
            matchScore: 92,
            status: 'active',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            title: 'Product Manager',
            company: 'DataViz Inc',
            description: 'Join our product team to drive the roadmap for our data visualization platform. You will work closely with engineering and design teams to deliver innovative solutions.',
            location: 'New York, NY',
            salaryRange: '$100k - $150k',
            jobUrl: 'https://dataviz.com/jobs/product-manager',
            matchScore: 85,
            status: 'active',
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            title: 'Data Analyst',
            company: 'Analytics Group',
            description: 'We need a detail-oriented Data Analyst to help us make data-driven decisions. You will analyze business metrics, create dashboards, and present insights to stakeholders.',
            location: 'Austin, TX',
            salaryRange: '$80k - $120k',
            jobUrl: 'https://analyticsgroup.com/careers/data-analyst',
            matchScore: 78,
            status: 'active',
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            title: 'UX Designer',
            company: 'DesignHub',
            description: 'Looking for a creative UX Designer to craft intuitive user experiences for our mobile and web applications. You will conduct user research and create high-fidelity prototypes.',
            location: 'Seattle, WA',
            salaryRange: '$90k - $130k',
            jobUrl: 'https://designhub.com/jobs/ux-designer',
            matchScore: 88,
            status: 'active',
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            title: 'Marketing Manager',
            company: 'MarketPro',
            description: 'We are hiring a Marketing Manager to lead our digital marketing campaigns and grow our brand presence. You will manage a team and oversee multi-channel marketing strategies.',
            location: 'Boston, MA',
            salaryRange: '$110k - $160k',
            jobUrl: 'https://marketpro.com/careers/marketing-manager',
            matchScore: 72,
            status: 'active',
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            title: 'DevOps Engineer',
            company: 'DevOps Solutions',
            description: 'Seeking a skilled DevOps Engineer to manage our cloud infrastructure and CI/CD pipelines. You will ensure high availability and implement automation best practices.',
            location: 'Remote',
            salaryRange: '$130k - $190k',
            jobUrl: 'https://devopssolutions.com/jobs/devops-engineer',
            matchScore: 95,
            status: 'active',
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            title: 'Frontend Developer',
            company: 'WebTech',
            description: 'Join our frontend team to build beautiful and responsive user interfaces using React and TypeScript. You will collaborate with designers to implement pixel-perfect designs.',
            location: 'Los Angeles, CA',
            salaryRange: '$95k - $140k',
            jobUrl: 'https://webtech.com/careers/frontend-developer',
            matchScore: 82,
            status: 'active',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            title: 'Data Scientist',
            company: 'AI Innovations',
            description: 'We are looking for a Data Scientist to develop machine learning models and drive AI initiatives. You will work with large datasets and deploy predictive models.',
            location: 'Chicago, IL',
            salaryRange: '$115k - $165k',
            jobUrl: 'https://aiinnovations.com/jobs/data-scientist',
            matchScore: 89,
            status: 'active',
            createdAt: new Date('2024-02-03').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        {
            title: 'Customer Success Manager',
            company: 'CustomerFirst',
            description: 'Join our customer success team to ensure client satisfaction and drive product adoption. You will build strong relationships and identify growth opportunities.',
            location: 'Denver, CO',
            salaryRange: '$85k - $125k',
            jobUrl: 'https://customerfirst.com/careers/customer-success',
            matchScore: 75,
            status: 'active',
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            title: 'Business Analyst',
            company: 'Analytics Group',
            description: 'We need a Business Analyst to bridge the gap between business stakeholders and technical teams. You will gather requirements and create detailed documentation.',
            location: 'Portland, OR',
            salaryRange: '$105k - $145k',
            jobUrl: 'https://analyticsgroup.com/careers/business-analyst',
            matchScore: 65,
            status: 'active',
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
    ];

    await db.insert(jobs).values(sampleJobs);
    
    console.log('✅ Jobs seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});