import { db } from '@/db';
import { leads, user } from '@/db/schema';
import { eq } from 'drizzle-orm';

async function main() {
    // First, get a valid user ID from the database
    const users = await db.select({ id: user.id }).from(user).limit(1);
    
    if (users.length === 0) {
        console.warn('⚠️  No users found in database. Please create a user first before seeding leads.');
        return;
    }
    
    const userId = users[0].id;
    console.log(`✅ Using user ID: ${userId}`);

    const baseDate = new Date('2024-12-05');
    
    const sampleLeads = [
        // Tech/Software Companies (6 leads)
        {
            userId,
            companyName: 'TechVision Solutions',
            contactName: 'Sarah Mitchell',
            contactEmail: 'sarah.mitchell@techvisionsolutions.com',
            contactPhone: '+1-415-555-0142',
            companyWebsite: 'https://techvisionsolutions.com',
            industry: 'Technology',
            location: 'San Francisco',
            companySize: '201-500',
            matchScore: 89,
            matchReason: 'Strong match for senior software engineering role. Company actively seeking expertise in full-stack development, microservices architecture, and cloud technologies.',
            status: 'contacted',
            notes: 'Initial outreach sent via email. Mentioned our expertise in React, Node.js, and AWS.',
            createdAt: new Date(baseDate.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId,
            companyName: 'CloudScale Systems',
            contactName: 'David Park',
            contactEmail: 'david.park@cloudscalesystems.com',
            contactPhone: '+1-206-555-0198',
            companyWebsite: 'https://cloudscalesystems.com',
            industry: 'SaaS',
            location: 'Seattle',
            companySize: '51-200',
            matchScore: 92,
            matchReason: 'Excellent fit for cloud infrastructure engineering. Company needs expertise in Kubernetes, Docker, and distributed systems architecture.',
            status: 'new',
            notes: null,
            createdAt: new Date(baseDate.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId,
            companyName: 'DataForge Inc',
            contactName: 'Jennifer Chen',
            contactEmail: 'jennifer.chen@dataforge.com',
            contactPhone: '+1-512-555-0176',
            companyWebsite: 'https://dataforge.com',
            industry: 'Technology',
            location: 'Austin',
            companySize: '101-500',
            matchScore: 87,
            matchReason: 'Great match for data engineering position. Company seeks proficiency in Python, SQL, data pipelines, and analytics platforms.',
            status: 'replied',
            notes: 'Positive response received. They want to schedule a call next week to discuss opportunities.',
            createdAt: new Date(baseDate.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId,
            companyName: 'Quantum Innovations',
            contactName: 'Michael Roberts',
            contactEmail: 'michael.roberts@quantuminnovations.com',
            contactPhone: '+1-617-555-0134',
            companyWebsite: 'https://quantuminnovations.com',
            industry: 'Technology',
            location: 'Boston',
            companySize: '501-1000',
            matchScore: 84,
            matchReason: 'Good alignment for senior developer role. Company values experience in agile methodologies, API development, and technical leadership.',
            status: 'new',
            notes: null,
            createdAt: new Date(baseDate.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId,
            companyName: 'ByteCraft Labs',
            contactName: 'Lisa Anderson',
            contactEmail: 'lisa.anderson@bytecraftlabs.com',
            contactPhone: '+1-212-555-0167',
            companyWebsite: 'https://bytecraftlabs.com',
            industry: 'SaaS',
            location: 'New York',
            companySize: '201-500',
            matchScore: 90,
            matchReason: 'Strong technical match for engineering team. Company looking for expertise in TypeScript, modern frameworks, and scalable system design.',
            status: 'new',
            notes: null,
            createdAt: new Date(baseDate.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId,
            companyName: 'Streamline Software',
            contactName: 'Robert Thompson',
            contactEmail: 'robert.thompson@streamlinesoftware.com',
            contactPhone: '+1-720-555-0145',
            companyWebsite: 'https://streamlinesoftware.com',
            industry: 'Technology',
            location: 'Denver',
            companySize: '51-200',
            matchScore: 86,
            matchReason: 'Solid match for full-stack development role. Company needs experience in React, Node.js, PostgreSQL, and CI/CD practices.',
            status: 'contacted',
            notes: 'Follow-up email sent with portfolio and GitHub profile.',
            createdAt: new Date(baseDate.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Marketing/Digital Companies (6 leads)
        {
            userId,
            companyName: 'BrandBoost Agency',
            contactName: 'Amanda Foster',
            contactEmail: 'amanda.foster@brandboost.com',
            contactPhone: '+1-212-555-0189',
            companyWebsite: 'https://brandboost.com',
            industry: 'Digital Marketing',
            location: 'New York',
            companySize: '51-200',
            matchScore: 88,
            matchReason: 'Excellent match for marketing leadership role. Company seeks expertise in digital strategy, campaign management, and team leadership.',
            status: 'new',
            notes: null,
            createdAt: new Date(baseDate.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId,
            companyName: 'Creative Pulse Marketing',
            contactName: 'James Martinez',
            contactEmail: 'james.martinez@creativepulse.com',
            contactPhone: '+1-323-555-0156',
            companyWebsite: 'https://creativepulse.com',
            industry: 'Digital Marketing',
            location: 'Los Angeles',
            companySize: '101-500',
            matchScore: 93,
            matchReason: 'Outstanding fit for senior marketing manager position. Company values experience in SEO, content marketing, analytics, and ROI optimization.',
            status: 'qualified',
            notes: 'Great conversation! Moving forward with formal interview process. They love our track record in digital campaigns.',
            createdAt: new Date(baseDate.getTime() - 13 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 11 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId,
            companyName: 'Digital Heights Studio',
            contactName: 'Rachel Kim',
            contactEmail: 'rachel.kim@digitalheights.com',
            contactPhone: '+1-312-555-0123',
            companyWebsite: 'https://digitalheights.com',
            industry: 'Digital Marketing',
            location: 'Chicago',
            companySize: '10-50',
            matchScore: 85,
            matchReason: 'Strong match for marketing strategist role. Company needs expertise in social media marketing, brand development, and influencer partnerships.',
            status: 'contacted',
            notes: 'Initial email sent highlighting our success with social media campaigns and brand growth strategies.',
            createdAt: new Date(baseDate.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId,
            companyName: 'Elevate Brand Partners',
            contactName: 'Daniel Wright',
            contactEmail: 'daniel.wright@elevatebrand.com',
            contactPhone: '+1-503-555-0178',
            companyWebsite: 'https://elevatebrand.com',
            industry: 'Marketing',
            location: 'Portland',
            companySize: '51-200',
            matchScore: 82,
            matchReason: 'Good alignment for marketing operations role. Company values experience in marketing automation, CRM systems, and performance analytics.',
            status: 'new',
            notes: null,
            createdAt: new Date(baseDate.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId,
            companyName: 'Momentum Digital',
            contactName: 'Emily Garcia',
            contactEmail: 'emily.garcia@momentumdigital.com',
            contactPhone: '+1-305-555-0192',
            companyWebsite: 'https://momentumdigital.com',
            industry: 'Digital Marketing',
            location: 'Miami',
            companySize: '201-500',
            matchScore: 87,
            matchReason: 'Excellent fit for digital marketing director position. Company seeks proven track record in paid advertising, email marketing, and conversion optimization.',
            status: 'replied',
            notes: 'Positive response. They are impressed with our experience and want to learn more about our approach to marketing strategy.',
            createdAt: new Date(baseDate.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId,
            companyName: 'Spark Creative Agency',
            contactName: 'Thomas Bennett',
            contactEmail: 'thomas.bennett@sparkcreative.com',
            contactPhone: '+1-415-555-0165',
            companyWebsite: 'https://sparkcreative.com',
            industry: 'Marketing',
            location: 'San Francisco',
            companySize: '10-50',
            matchScore: 80,
            matchReason: 'Solid match for creative marketing manager. Company values expertise in brand storytelling, content strategy, and creative campaign execution.',
            status: 'new',
            notes: null,
            createdAt: new Date(baseDate.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Sales/B2B Companies (6 leads)
        {
            userId,
            companyName: 'Revenue Accelerators',
            contactName: 'Christopher Davis',
            contactEmail: 'christopher.davis@revenueaccelerators.com',
            contactPhone: '+1-617-555-0187',
            companyWebsite: 'https://revenueaccelerators.com',
            industry: 'B2B Sales',
            location: 'Boston',
            companySize: '101-500',
            matchScore: 72,
            matchReason: 'Basic match for sales operations role. Company seeks experience in sales process optimization and CRM management.',
            status: 'rejected',
            notes: 'Company decided to go with internal candidate. They appreciated our interest and will keep us in mind for future opportunities.',
            createdAt: new Date(baseDate.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId,
            companyName: 'Growth Partners LLC',
            contactName: 'Victoria Moore',
            contactEmail: 'victoria.moore@growthpartners.com',
            contactPhone: '+1-512-555-0143',
            companyWebsite: 'https://growthpartners.com',
            industry: 'B2B Sales',
            location: 'Austin',
            companySize: '51-200',
            matchScore: 91,
            matchReason: 'Strong match for sales director position. Company needs proven leadership in B2B sales, account management, and revenue growth strategies.',
            status: 'new',
            notes: null,
            createdAt: new Date(baseDate.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId,
            companyName: 'Summit Sales Solutions',
            contactName: 'Matthew Taylor',
            contactEmail: 'matthew.taylor@summitsales.com',
            contactPhone: '+1-206-555-0159',
            companyWebsite: 'https://summitsales.com',
            industry: 'SaaS',
            location: 'Seattle',
            companySize: '201-500',
            matchScore: 89,
            matchReason: 'Excellent fit for enterprise sales leadership. Company values expertise in SaaS sales cycles, enterprise account management, and team development.',
            status: 'replied',
            notes: 'Very interested! They want to schedule a call to discuss our experience with enterprise sales and team leadership.',
            createdAt: new Date(baseDate.getTime() - 11 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId,
            companyName: 'Enterprise Growth Advisors',
            contactName: 'Jessica Wilson',
            contactEmail: 'jessica.wilson@enterprisegrowth.com',
            contactPhone: '+1-212-555-0194',
            companyWebsite: 'https://enterprisegrowth.com',
            industry: 'B2B Sales',
            location: 'New York',
            companySize: '501-1000',
            matchScore: 94,
            matchReason: 'Outstanding match for VP of Sales role. Company seeks proven track record in scaling sales organizations, strategic planning, and partnership development.',
            status: 'contacted',
            notes: 'Sent comprehensive overview of our sales leadership experience and revenue achievements. Highlighted our success in scaling teams.',
            createdAt: new Date(baseDate.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId,
            companyName: 'Strategic Sales Partners',
            contactName: 'Brandon Lee',
            contactEmail: 'brandon.lee@strategicsales.com',
            contactPhone: '+1-312-555-0171',
            companyWebsite: 'https://strategicsales.com',
            industry: 'B2B Sales',
            location: 'Chicago',
            companySize: '10-50',
            matchScore: 83,
            matchReason: 'Good match for senior sales consultant role. Company values experience in consultative selling, client relationship management, and deal closing.',
            status: 'new',
            notes: null,
            createdAt: new Date(baseDate.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId,
            companyName: 'Apex Revenue Systems',
            contactName: 'Nicole Johnson',
            contactEmail: 'nicole.johnson@apexrevenue.com',
            contactPhone: '+1-415-555-0186',
            companyWebsite: 'https://apexrevenue.com',
            industry: 'SaaS',
            location: 'San Francisco',
            companySize: '201-500',
            matchScore: 95,
            matchReason: 'Perfect match for head of sales position. Company needs expertise in SaaS revenue operations, sales enablement, pipeline management, and executive leadership.',
            status: 'contacted',
            notes: 'Strong initial conversation. They are actively looking for someone with our background. Follow-up meeting scheduled.',
            createdAt: new Date(baseDate.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(leads).values(sampleLeads);
    
    console.log('✅ Leads seeder completed successfully');
    console.log(`   - Created 18 leads for user ${userId}`);
    console.log('   - 6 Tech/Software companies');
    console.log('   - 6 Marketing/Digital agencies');
    console.log('   - 6 B2B/SaaS Sales companies');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});